## ASSIGNMENT 1 - Backpropagation

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# set up Data
X = np.eye(8)    # input
Y = X.copy()     # output

n_input = 8
n_hidden = 3
n_output = 8

np.random.seed(0)   # for reproducibility

W1 = np.random.randn(n_input, n_hidden) * 0.1
b1 = np.zeros((1, n_hidden))
W2 = np.random.randn(n_hidden, n_output) * 0.1
b2 = np.zeros((1, n_output))

print(W1)
print(b1)
print(W2)
print(b2)


[[ 0.17640523  0.04001572  0.0978738 ]
 [ 0.22408932  0.1867558  -0.09772779]
 [ 0.09500884 -0.01513572 -0.01032189]
 [ 0.04105985  0.01440436  0.14542735]
 [ 0.07610377  0.0121675   0.04438632]
 [ 0.03336743  0.14940791 -0.02051583]
 [ 0.03130677 -0.08540957 -0.25529898]
 [ 0.06536186  0.08644362 -0.0742165 ]]
[[0. 0. 0.]]
[[ 0.22697546 -0.14543657  0.00457585 -0.01871839  0.15327792  0.14693588
   0.01549474  0.03781625]
 [-0.08877857 -0.19807965 -0.03479121  0.0156349   0.12302907  0.12023798
  -0.03873268 -0.03023028]
 [-0.1048553  -0.14200179 -0.17062702  0.19507754 -0.05096522 -0.04380743
  -0.12527954  0.07774904]]
[[0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
# Activation Function

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)
