## ASSIGNMENT 1 - Backpropagation

In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
# set up Data
X = np.eye(8)    # input
Y = X.copy()     # output

n_input = 8
n_hidden = 3
n_output = 8

np.random.seed(0)   # for reproducibility

W1 = np.random.randn(n_input, n_hidden) * 0.1
b1 = np.zeros((1, n_hidden))
W2 = np.random.randn(n_hidden, n_output) * 0.1
b2 = np.zeros((1, n_output))

print(W1.shape, b1.shape)
print(W2.shape, b2.shape)
print(X.shape, Y.shape)


(8, 3) (1, 3)
(3, 8) (1, 8)
(8, 8) (8, 8)


In [36]:
# Activation Function

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)    


In [37]:
# Feedforward Phase 

def feedforwrd(X): 
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)  # hidden layer activations 

    z2 = np.dot(a1, W2) + b2
    Y_hat = sigmoid(z2)  # final output 

    return z1, z2, a1, Y_hat

In [38]:
# Backpropagation Phase 

def backprop(X, Y, a1, Y_hat, z1, z2, lr = 0.5) : 
    global W1, b1, W2, b2

    # Output layer error 
    error = Y_hat - Y
    dY_hat = error * sigmoid_derivative(z2) 

    # Hidden layer error 
    d_a1 = np.dot(dY_hat, W2.T) * sigmoid_derivative(z1)

    # Update weights and biases
    W2 -= np.dot(a1.T, dY_hat) * lr
    b2 -= np.sum(dY_hat, axis = 0, keepdims = True) * lr 

    W1 -= np.dot(X.T, d_a1) * lr
    b1 -= np.sum(d_a1, axis = 0, keepdims = True) * lr

    return np.mean(np.abs(Y - Y_hat))

In [39]:
# --- Training loop ---

def mse_loss(Y_hat, Y):
    return 0.5 * np.mean((Y_hat - Y)**2)

epochs = 10000
lr = 0.5

for epoch in range(epochs):
    # --- Forward ---
    z1, z2, a1, Y_hat = feedforwrd(X)

    # --- Compute loss ---
    loss = mse_loss(Y_hat, Y)

    # --- Backpropagation & update ---
    mae = backprop(X, Y, a1, Y_hat, z1, z2, lr)

    # --- Monitor progress every 1000 epochs ---
    if epoch % 1000 == 0:
        print(f"Epoch {epoch:5d} | MSE loss: {loss:.6f} | MAE: {mae:.6f}")

# --- Final output check ---
print("\nFinal predictions after training:")
print(np.round(Y_hat, 3))


Epoch     0 | MSE loss: 0.125112 | MAE: 0.499326
Epoch  1000 | MSE loss: 0.008452 | MAE: 0.069709
Epoch  2000 | MSE loss: 0.001346 | MAE: 0.033687
Epoch  3000 | MSE loss: 0.000631 | MAE: 0.023704
Epoch  4000 | MSE loss: 0.000418 | MAE: 0.019411
Epoch  5000 | MSE loss: 0.000313 | MAE: 0.016833
Epoch  6000 | MSE loss: 0.000250 | MAE: 0.015063
Epoch  7000 | MSE loss: 0.000208 | MAE: 0.013751
Epoch  8000 | MSE loss: 0.000178 | MAE: 0.012729
Epoch  9000 | MSE loss: 0.000156 | MAE: 0.011903

Final predictions after training:
[[0.969 0.    0.    0.015 0.028 0.    0.014 0.   ]
 [0.    0.968 0.    0.    0.028 0.015 0.017 0.   ]
 [0.    0.    0.969 0.018 0.    0.02  0.02  0.   ]
 [0.024 0.    0.016 0.973 0.    0.    0.    0.022]
 [0.01  0.015 0.    0.    0.958 0.    0.    0.016]
 [0.    0.025 0.016 0.    0.    0.972 0.    0.023]
 [0.026 0.024 0.017 0.    0.    0.    0.972 0.   ]
 [0.    0.    0.    0.016 0.027 0.016 0.    0.969]]


In [40]:
predicted_classes = np.argmax(Y_hat, axis=1)
true_classes = np.argmax(Y, axis=1)
accuracy = np.mean(predicted_classes == true_classes)
print("Accuracy:", accuracy)

Accuracy: 1.0
